extern const GeoLayout tilt_platform_geo[];
extern u8 tilt_platform_EARTHWORM_JIM_3D_0A73F969_0_2_all_ci8[];
extern u8 tilt_platform_EARTHWORM_JIM_3D_0A73F969_0_2_all_ci8_pal_rgba16[];
extern u8 tilt_platform_EARTHWORM_JIM_3D_0A73F969_0_4_all_ci8[];
extern u8 tilt_platform_EARTHWORM_JIM_3D_0A73F969_0_4_all_ci8_pal_rgba16[];
extern Vtx tilt_platform_Cube_mesh_layer_1_vtx_0[24];
extern Gfx tilt_platform_Cube_mesh_layer_1_tri_0[];
extern Vtx tilt_platform_Cube_mesh_layer_1_vtx_1[29];
extern Gfx tilt_platform_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_tilt_platform_f3dlite_material_002_layer1[];
extern Gfx mat_revert_tilt_platform_f3dlite_material_002_layer1[];
extern Gfx mat_tilt_platform_f3dlite_material[];
extern Gfx mat_revert_tilt_platform_f3dlite_material[];
extern Gfx tilt_platform_Cube_mesh_layer_1[];
extern Gfx tilt_platform_material_revert_render_settings[];
