extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern const GeoLayout ccm_area_2_geo[];
extern const GeoLayout ccm_area_2[];
extern const Collision ccm_area_2_collision[];
extern const MacroObject ccm_area_2_macro_objs[];
extern const GeoLayout ccm_area_3_geo[];
extern const GeoLayout ccm_area_3[];
extern const Collision ccm_area_3_collision[];
extern const MacroObject ccm_area_3_macro_objs[];
extern const GeoLayout ccm_area_4_geo[];
extern const GeoLayout ccm_area_4[];
extern const Collision ccm_area_4_collision[];
extern const MacroObject ccm_area_4_macro_objs[];
extern const GeoLayout ccm_area_5_geo[];
extern const GeoLayout ccm_area_5[];
extern const Collision ccm_area_5_collision[];
extern const MacroObject ccm_area_5_macro_objs[];
extern Lights1 ccm_dl_f3dlite_material_013_lights;
extern Lights1 ccm_dl_f3dlite_material_012_lights;
extern Lights1 ccm_dl_f3dlite_material_030_lights;
extern Lights1 ccm_dl_f3dlite_material_034_lights;
extern Lights1 ccm_dl_f3dlite_material_003_lights;
extern Lights1 ccm_dl_f3dlite_material_038_lights;
extern u8 ccm_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvW_i8[];
extern u8 ccm_dl_Strip_ia8[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_pal_rgba16[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_copy[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_pal_rgba16_copy[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_copy_copy[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_pal_rgba16_copy_copy[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_copy_copy_copy[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_pal_rgba16_copy_copy_copy[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_0[82];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_1[10];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Cube_mesh_layer_5_vtx_0[70];
extern Gfx ccm_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_001_mesh_layer_1_vtx_0[82];
extern Gfx ccm_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_001_mesh_layer_1_vtx_1[10];
extern Gfx ccm_dl_Cube_001_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Cube_001_mesh_layer_5_vtx_0[70];
extern Gfx ccm_dl_Cube_001_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_World_mesh_layer_1_vtx_0[84];
extern Gfx ccm_dl_World_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_002_mesh_layer_1_vtx_0[82];
extern Gfx ccm_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_002_mesh_layer_1_vtx_1[10];
extern Gfx ccm_dl_Cube_002_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Cube_002_mesh_layer_5_vtx_0[70];
extern Gfx ccm_dl_Cube_002_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_World_002_mesh_layer_1_vtx_0[68];
extern Gfx ccm_dl_World_002_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_004_mesh_layer_1_vtx_0[82];
extern Gfx ccm_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_004_mesh_layer_1_vtx_1[10];
extern Gfx ccm_dl_Cube_004_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Cube_004_mesh_layer_5_vtx_0[70];
extern Gfx ccm_dl_Cube_004_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_World_001_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_World_001_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_005_mesh_layer_1_vtx_0[82];
extern Gfx ccm_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_005_mesh_layer_1_vtx_1[10];
extern Gfx ccm_dl_Cube_005_mesh_layer_1_tri_1[];
extern Vtx ccm_dl_Cube_005_mesh_layer_5_vtx_0[70];
extern Gfx ccm_dl_Cube_005_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Plane_004_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_Plane_004_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_World_003_mesh_layer_1_vtx_0[39];
extern Gfx ccm_dl_World_003_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_black_002[];
extern Gfx mat_revert_ccm_dl_black_002[];
extern Gfx mat_ccm_dl_f3dlite_material_013[];
extern Gfx mat_ccm_dl_f3dlite_material_040[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_040[];
extern Gfx mat_ccm_dl_f3dlite_material_012[];
extern Gfx mat_ccm_dl_f3dlite_material_030[];
extern Gfx mat_ccm_dl_f3dlite_material_015[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_015[];
extern Gfx mat_ccm_dl_f3dlite_material_034[];
extern Gfx mat_ccm_dl_f3dlite_material_032[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_032[];
extern Gfx mat_ccm_dl_f3dlite_material_003[];
extern Gfx mat_ccm_dl_f3dlite_material_005[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_005[];
extern Gfx mat_ccm_dl_f3dlite_material_038[];
extern Gfx mat_ccm_dl_f3dlite_material_036[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_036[];
extern Gfx ccm_dl_Cube_mesh_layer_1[];
extern Gfx ccm_dl_Cube_mesh_layer_5[];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
extern Gfx ccm_dl_Cube_001_mesh_layer_1[];
extern Gfx ccm_dl_Cube_001_mesh_layer_5[];
extern Gfx ccm_dl_Plane_001_mesh_layer_1[];
extern Gfx ccm_dl_World_mesh_layer_1[];
extern Gfx ccm_dl_Cube_002_mesh_layer_1[];
extern Gfx ccm_dl_Cube_002_mesh_layer_5[];
extern Gfx ccm_dl_Plane_002_mesh_layer_1[];
extern Gfx ccm_dl_World_002_mesh_layer_1[];
extern Gfx ccm_dl_Cube_004_mesh_layer_1[];
extern Gfx ccm_dl_Cube_004_mesh_layer_5[];
extern Gfx ccm_dl_Plane_003_mesh_layer_1[];
extern Gfx ccm_dl_World_001_mesh_layer_1[];
extern Gfx ccm_dl_Cube_005_mesh_layer_1[];
extern Gfx ccm_dl_Cube_005_mesh_layer_5[];
extern Gfx ccm_dl_Plane_004_mesh_layer_1[];
extern Gfx ccm_dl_World_003_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
