extern const GeoLayout ccm_area_1_geo[];
extern const GeoLayout ccm_area_1[];
extern const Collision ccm_area_1_collision[];
extern const MacroObject ccm_area_1_macro_objs[];
extern Lights1 ccm_dl_noise_lights;
extern Lights1 ccm_dl_f3dlite_material_001_lights;
extern u8 ccm_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8[];
extern u8 ccm_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16[];
extern u8 ccm_dl_GALE01_05f0c180_3_rgba16[];
extern u8 ccm_dl_Moon_i8[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8[];
extern u8 ccm_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_pal_rgba16[];
extern Vtx ccm_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_6_vtx_0[15];
extern Gfx ccm_dl_Cube_mesh_layer_6_tri_0[];
extern Vtx ccm_dl_Cube_mesh_layer_5_vtx_0[32];
extern Gfx ccm_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx ccm_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx ccm_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ccm_dl_World_mesh_layer_1_vtx_0[24];
extern Gfx ccm_dl_World_mesh_layer_1_tri_0[];
extern Gfx mat_ccm_dl_black[];
extern Gfx mat_revert_ccm_dl_black[];
extern Gfx mat_ccm_dl_stars[];
extern Gfx mat_revert_ccm_dl_stars[];
extern Gfx mat_ccm_dl_noise[];
extern Gfx mat_revert_ccm_dl_noise[];
extern Gfx mat_ccm_dl_f3dlite_material_001[];
extern Gfx mat_ccm_dl_f3dlite_material_005[];
extern Gfx mat_revert_ccm_dl_f3dlite_material_005[];
extern Gfx ccm_dl_Cube_mesh_layer_1[];
extern Gfx ccm_dl_Cube_mesh_layer_6[];
extern Gfx ccm_dl_Cube_mesh_layer_5[];
extern Gfx ccm_dl_Plane_mesh_layer_1[];
extern Gfx ccm_dl_World_mesh_layer_1[];
extern Gfx ccm_dl_material_revert_render_settings[];
