extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_noise_lights;
extern Lights1 castle_grounds_dl_f3dlite_material_015_lights;
extern u8 castle_grounds_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8[];
extern u8 castle_grounds_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16[];
extern u8 castle_grounds_dl_GALE01_05f0c180_3_rgba16[];
extern u8 castle_grounds_dl_Moon_i8[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_5_vtx_0[15];
extern Gfx castle_grounds_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx castle_grounds_dl_Cube_mesh_layer_5_vtx_1[32];
extern Gfx castle_grounds_dl_Cube_mesh_layer_5_tri_1[];
extern Vtx castle_grounds_dl_Mario_Platform_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_Mario_Platform_mesh_layer_1_tri_0[];
extern Gfx mat_castle_grounds_dl_black[];
extern Gfx mat_revert_castle_grounds_dl_black[];
extern Gfx mat_castle_grounds_dl_stars[];
extern Gfx mat_revert_castle_grounds_dl_stars[];
extern Gfx mat_castle_grounds_dl_noise[];
extern Gfx mat_revert_castle_grounds_dl_noise[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_015[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_1[];
extern Gfx castle_grounds_dl_Cube_mesh_layer_5[];
extern Gfx castle_grounds_dl_Mario_Platform_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
