#include <PR/ultratypes.h>
#include <PR/gbi.h>

#include "macros.h"
#include "surface_terrains.h"
#include "types.h"
#include "make_const_nonconst.h"

#include "tilt_platform_wide/model.inc.c"
#include "tilt_platform_wide/collision.inc.c"
#include "tilt_platform/collision.inc.c"
#include "tilt_platform/model.inc.c"
#include "tilt_box/collision.inc.c"
#include "tilt_box/model.inc.c"
#include "slide_platform_small/collision.inc.c"
#include "slide_platform_small/model.inc.c"
#include "level_button/model.inc.c"
#include "selector/model.inc.c"
#include "star_ball/model.inc.c"
#include "pinball/model.inc.c"
#include "pinball/collision.inc.c"
#include "fan/model.inc.c"
#include "credits_button/model.inc.c"
#include "level_button_star/model.inc.c"
#include "gate/collision.inc.c"
#include "gate/model.inc.c"