#include "levels/maple_treewway/area_1/collision.inc.c"
#include "levels/maple_treewway/area_1/macro.inc.c"
#include "levels/maple_treewway/area_1/spline.inc.c"
#include "levels/maple_treewway/area_2/collision.inc.c"
#include "levels/maple_treewway/area_2/macro.inc.c"
#include "levels/maple_treewway/area_2/spline.inc.c"
#include "levels/maple_treewway/model.inc.c"
