extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_noise_lights;
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16[];
extern u8 bob_dl_GALE01_05f0c180_3_rgba16[];
extern u8 bob_dl_Moon_i8[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_6_vtx_0[15];
extern Gfx bob_dl_Cube_mesh_layer_6_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_0[32];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_black[];
extern Gfx mat_revert_bob_dl_black[];
extern Gfx mat_bob_dl_stars[];
extern Gfx mat_revert_bob_dl_stars[];
extern Gfx mat_bob_dl_noise[];
extern Gfx mat_revert_bob_dl_noise[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_6[];
extern Gfx bob_dl_Cube_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
