extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern const GeoLayout bob_area_5_geo[];
extern const GeoLayout bob_area_5[];
extern const Collision bob_area_5_collision[];
extern const MacroObject bob_area_5_macro_objs[];
extern Lights1 bob_dl_noise_lights;
extern Lights1 bob_dl_f3dlite_material_001_lights;
extern Lights1 bob_dl_noise_001_lights;
extern Lights1 bob_dl_f3dlite_material_003_lights;
extern Lights1 bob_dl_noise_002_lights;
extern Lights1 bob_dl_f3dlite_material_007_lights;
extern Lights1 bob_dl_noise_003_lights;
extern Lights1 bob_dl_f3dlite_material_010_lights;
extern Lights1 bob_dl_noise_004_lights;
extern Lights1 bob_dl_f3dlite_material_013_lights;
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16[];
extern u8 bob_dl_GALE01_05f0c180_3_rgba16[];
extern u8 bob_dl_Moon_i8[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_copy[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16_copy[];
extern u8 bob_dl_GALE01_05f0c180_3_rgba16_copy[];
extern u8 bob_dl_Moon_i8_copy[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_copy_copy[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16_copy_copy[];
extern u8 bob_dl_GALE01_05f0c180_3_rgba16_copy_copy[];
extern u8 bob_dl_Moon_i8_copy_copy[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_copy_copy_copy[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16_copy_copy_copy[];
extern u8 bob_dl_GALE01_05f0c180_3_rgba16_copy_copy_copy[];
extern u8 bob_dl_Moon_i8_copy_copy_copy[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_copy_copy_copy_copy[];
extern u8 bob_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16_copy_copy_copy_copy[];
extern u8 bob_dl_GALE01_05f0c180_3_rgba16_copy_copy_copy_copy[];
extern u8 bob_dl_Moon_i8_copy_copy_copy_copy[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_6_vtx_0[15];
extern Gfx bob_dl_Cube_mesh_layer_6_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_5_vtx_0[32];
extern Gfx bob_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_6_vtx_0[15];
extern Gfx bob_dl_Cube_001_mesh_layer_6_tri_0[];
extern Vtx bob_dl_Cube_001_mesh_layer_5_vtx_0[32];
extern Gfx bob_dl_Cube_001_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_6_vtx_0[15];
extern Gfx bob_dl_Cube_002_mesh_layer_6_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_5_vtx_0[32];
extern Gfx bob_dl_Cube_002_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_003_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_003_mesh_layer_6_vtx_0[15];
extern Gfx bob_dl_Cube_003_mesh_layer_6_tri_0[];
extern Vtx bob_dl_Cube_003_mesh_layer_5_vtx_0[32];
extern Gfx bob_dl_Cube_003_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_004_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_004_mesh_layer_6_vtx_0[15];
extern Gfx bob_dl_Cube_004_mesh_layer_6_tri_0[];
extern Vtx bob_dl_Cube_004_mesh_layer_5_vtx_0[32];
extern Gfx bob_dl_Cube_004_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_004_mesh_layer_1_vtx_0[4];
extern Gfx bob_dl_Plane_004_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_black[];
extern Gfx mat_revert_bob_dl_black[];
extern Gfx mat_bob_dl_stars[];
extern Gfx mat_revert_bob_dl_stars[];
extern Gfx mat_bob_dl_noise[];
extern Gfx mat_revert_bob_dl_noise[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_black_001[];
extern Gfx mat_revert_bob_dl_black_001[];
extern Gfx mat_bob_dl_stars_001[];
extern Gfx mat_revert_bob_dl_stars_001[];
extern Gfx mat_bob_dl_noise_001[];
extern Gfx mat_revert_bob_dl_noise_001[];
extern Gfx mat_bob_dl_f3dlite_material_003[];
extern Gfx mat_bob_dl_black_002[];
extern Gfx mat_revert_bob_dl_black_002[];
extern Gfx mat_bob_dl_stars_002[];
extern Gfx mat_revert_bob_dl_stars_002[];
extern Gfx mat_bob_dl_noise_002[];
extern Gfx mat_revert_bob_dl_noise_002[];
extern Gfx mat_bob_dl_f3dlite_material_007[];
extern Gfx mat_bob_dl_black_003[];
extern Gfx mat_revert_bob_dl_black_003[];
extern Gfx mat_bob_dl_stars_003[];
extern Gfx mat_revert_bob_dl_stars_003[];
extern Gfx mat_bob_dl_noise_003[];
extern Gfx mat_revert_bob_dl_noise_003[];
extern Gfx mat_bob_dl_f3dlite_material_010[];
extern Gfx mat_bob_dl_black_004[];
extern Gfx mat_revert_bob_dl_black_004[];
extern Gfx mat_bob_dl_stars_004[];
extern Gfx mat_revert_bob_dl_stars_004[];
extern Gfx mat_bob_dl_noise_004[];
extern Gfx mat_revert_bob_dl_noise_004[];
extern Gfx mat_bob_dl_f3dlite_material_013[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_6[];
extern Gfx bob_dl_Cube_mesh_layer_5[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_001_mesh_layer_6[];
extern Gfx bob_dl_Cube_001_mesh_layer_5[];
extern Gfx bob_dl_Plane_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_6[];
extern Gfx bob_dl_Cube_002_mesh_layer_5[];
extern Gfx bob_dl_Plane_002_mesh_layer_1[];
extern Gfx bob_dl_Cube_003_mesh_layer_1[];
extern Gfx bob_dl_Cube_003_mesh_layer_6[];
extern Gfx bob_dl_Cube_003_mesh_layer_5[];
extern Gfx bob_dl_Plane_003_mesh_layer_1[];
extern Gfx bob_dl_Cube_004_mesh_layer_1[];
extern Gfx bob_dl_Cube_004_mesh_layer_6[];
extern Gfx bob_dl_Cube_004_mesh_layer_5[];
extern Gfx bob_dl_Plane_004_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
