extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_noise_001_lights;
extern Lights1 wf_dl_f3dlite_material_001_lights;
extern u8 wf_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8[];
extern u8 wf_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16[];
extern u8 wf_dl_GALE01_05f0c180_3_rgba16[];
extern u8 wf_dl_Moon_i8[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_mesh_layer_6_vtx_0[15];
extern Gfx wf_dl_Cube_mesh_layer_6_tri_0[];
extern Vtx wf_dl_Cube_mesh_layer_5_vtx_0[32];
extern Gfx wf_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_black_001[];
extern Gfx mat_revert_wf_dl_black_001[];
extern Gfx mat_wf_dl_stars_001[];
extern Gfx mat_revert_wf_dl_stars_001[];
extern Gfx mat_wf_dl_noise_001[];
extern Gfx mat_revert_wf_dl_noise_001[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx wf_dl_Cube_mesh_layer_1[];
extern Gfx wf_dl_Cube_mesh_layer_6[];
extern Gfx wf_dl_Cube_mesh_layer_5[];
extern Gfx wf_dl_Plane_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
