extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const MacroObject wf_area_3_macro_objs[];
extern const GeoLayout wf_area_4_geo[];
extern const GeoLayout wf_area_4[];
extern const Collision wf_area_4_collision[];
extern const MacroObject wf_area_4_macro_objs[];
extern const GeoLayout wf_area_5_geo[];
extern const GeoLayout wf_area_5[];
extern const Collision wf_area_5_collision[];
extern const MacroObject wf_area_5_macro_objs[];
extern Lights1 wf_dl_noise_lights;
extern Lights1 wf_dl_f3dlite_material_001_lights;
extern Lights1 wf_dl_noise_003_lights;
extern Lights1 wf_dl_f3dlite_material_004_lights;
extern Lights1 wf_dl_noise_006_lights;
extern Lights1 wf_dl_f3dlite_material_008_lights;
extern Lights1 wf_dl_noise_007_lights;
extern Lights1 wf_dl_f3dlite_material_015_lights;
extern Lights1 wf_dl_noise_008_lights;
extern Lights1 wf_dl_f3dlite_material_019_lights;
extern u8 wf_dl__0x24881_rgba16[];
extern u8 wf_dl_GALE01_05f0c180__rgba16[];
extern u8 wf_dl__0x24881_rgba16_copy[];
extern u8 wf_dl_GALE01_05f0c180__rgba16_copy[];
extern u8 wf_dl__0x24881_rgba16_copy_copy[];
extern u8 wf_dl_GALE01_05f0c180__rgba16_copy_copy[];
extern u8 wf_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8[];
extern u8 wf_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_pal_rgba16[];
extern u8 wf_dl__0x24881_rgba16_copy_copy_copy[];
extern u8 wf_dl_GALE01_05f0c180__rgba16_copy_copy_copy[];
extern u8 wf_dl__0x24881_rgba16_copy_copy_copy_copy[];
extern u8 wf_dl_GALE01_05f0c180__rgba16_copy_copy_copy_copy[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_mesh_layer_6_vtx_0[15];
extern Gfx wf_dl_Cube_mesh_layer_6_tri_0[];
extern Vtx wf_dl_Cube_mesh_layer_5_vtx_0[32];
extern Gfx wf_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_001_mesh_layer_6_vtx_0[15];
extern Gfx wf_dl_Cube_001_mesh_layer_6_tri_0[];
extern Vtx wf_dl_Cube_001_mesh_layer_5_vtx_0[32];
extern Gfx wf_dl_Cube_001_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_002_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_002_mesh_layer_6_vtx_0[15];
extern Gfx wf_dl_Cube_002_mesh_layer_6_tri_0[];
extern Vtx wf_dl_Cube_002_mesh_layer_5_vtx_0[32];
extern Gfx wf_dl_Cube_002_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx wf_dl_World_mesh_layer_1_vtx_0[46];
extern Gfx wf_dl_World_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_004_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_004_mesh_layer_6_vtx_0[15];
extern Gfx wf_dl_Cube_004_mesh_layer_6_tri_0[];
extern Vtx wf_dl_Cube_004_mesh_layer_5_vtx_0[32];
extern Gfx wf_dl_Cube_004_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Plane_004_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_004_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_005_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_005_mesh_layer_6_vtx_0[15];
extern Gfx wf_dl_Cube_005_mesh_layer_6_tri_0[];
extern Vtx wf_dl_Cube_005_mesh_layer_5_vtx_0[32];
extern Gfx wf_dl_Cube_005_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Plane_005_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_005_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_black[];
extern Gfx mat_revert_wf_dl_black[];
extern Gfx mat_wf_dl_stars[];
extern Gfx mat_revert_wf_dl_stars[];
extern Gfx mat_wf_dl_noise[];
extern Gfx mat_revert_wf_dl_noise[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_wf_dl_black_003[];
extern Gfx mat_revert_wf_dl_black_003[];
extern Gfx mat_wf_dl_stars_003[];
extern Gfx mat_revert_wf_dl_stars_003[];
extern Gfx mat_wf_dl_noise_003[];
extern Gfx mat_revert_wf_dl_noise_003[];
extern Gfx mat_wf_dl_f3dlite_material_004[];
extern Gfx mat_wf_dl_black_006[];
extern Gfx mat_revert_wf_dl_black_006[];
extern Gfx mat_wf_dl_stars_006[];
extern Gfx mat_revert_wf_dl_stars_006[];
extern Gfx mat_wf_dl_noise_006[];
extern Gfx mat_revert_wf_dl_noise_006[];
extern Gfx mat_wf_dl_f3dlite_material_008[];
extern Gfx mat_wf_dl_f3dlite_material_006[];
extern Gfx mat_revert_wf_dl_f3dlite_material_006[];
extern Gfx mat_wf_dl_black_007[];
extern Gfx mat_revert_wf_dl_black_007[];
extern Gfx mat_wf_dl_stars_007[];
extern Gfx mat_revert_wf_dl_stars_007[];
extern Gfx mat_wf_dl_noise_007[];
extern Gfx mat_revert_wf_dl_noise_007[];
extern Gfx mat_wf_dl_f3dlite_material_015[];
extern Gfx mat_wf_dl_black_008[];
extern Gfx mat_revert_wf_dl_black_008[];
extern Gfx mat_wf_dl_stars_008[];
extern Gfx mat_revert_wf_dl_stars_008[];
extern Gfx mat_wf_dl_noise_008[];
extern Gfx mat_revert_wf_dl_noise_008[];
extern Gfx mat_wf_dl_f3dlite_material_019[];
extern Gfx wf_dl_Cube_mesh_layer_1[];
extern Gfx wf_dl_Cube_mesh_layer_6[];
extern Gfx wf_dl_Cube_mesh_layer_5[];
extern Gfx wf_dl_Plane_mesh_layer_1[];
extern Gfx wf_dl_Cube_001_mesh_layer_1[];
extern Gfx wf_dl_Cube_001_mesh_layer_6[];
extern Gfx wf_dl_Cube_001_mesh_layer_5[];
extern Gfx wf_dl_Plane_001_mesh_layer_1[];
extern Gfx wf_dl_Cube_002_mesh_layer_1[];
extern Gfx wf_dl_Cube_002_mesh_layer_6[];
extern Gfx wf_dl_Cube_002_mesh_layer_5[];
extern Gfx wf_dl_Plane_002_mesh_layer_1[];
extern Gfx wf_dl_World_mesh_layer_1[];
extern Gfx wf_dl_Cube_004_mesh_layer_1[];
extern Gfx wf_dl_Cube_004_mesh_layer_6[];
extern Gfx wf_dl_Cube_004_mesh_layer_5[];
extern Gfx wf_dl_Plane_004_mesh_layer_1[];
extern Gfx wf_dl_Cube_005_mesh_layer_1[];
extern Gfx wf_dl_Cube_005_mesh_layer_6[];
extern Gfx wf_dl_Cube_005_mesh_layer_5[];
extern Gfx wf_dl_Plane_005_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
