extern const GeoLayout tilt_platform_wide_geo[];
extern u8 tilt_platform_wide_EARTHWORM_JIM_3D_0A73F969_0_2_all_ci8[];
extern u8 tilt_platform_wide_EARTHWORM_JIM_3D_0A73F969_0_2_all_ci8_pal_rgba16[];
extern Vtx tilt_platform_wide_Cube_mesh_layer_1_vtx_0[24];
extern Gfx tilt_platform_wide_Cube_mesh_layer_1_tri_0[];
extern Gfx mat_tilt_platform_wide_f3dlite_material_002[];
extern Gfx mat_revert_tilt_platform_wide_f3dlite_material_002[];
extern Gfx tilt_platform_wide_Cube_mesh_layer_1[];
extern Gfx tilt_platform_wide_material_revert_render_settings[];
