extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern const GeoLayout jrb_area_2_geo[];
extern const GeoLayout jrb_area_2[];
extern const Collision jrb_area_2_collision[];
extern const MacroObject jrb_area_2_macro_objs[];
extern const GeoLayout jrb_area_3_geo[];
extern const GeoLayout jrb_area_3[];
extern const Collision jrb_area_3_collision[];
extern const MacroObject jrb_area_3_macro_objs[];
extern const GeoLayout jrb_area_4_geo[];
extern const GeoLayout jrb_area_4[];
extern const Collision jrb_area_4_collision[];
extern const MacroObject jrb_area_4_macro_objs[];
extern const GeoLayout jrb_area_5_geo[];
extern const GeoLayout jrb_area_5[];
extern const Collision jrb_area_5_collision[];
extern const MacroObject jrb_area_5_macro_objs[];
extern Lights1 jrb_dl_noise_lights;
extern Lights1 jrb_dl_f3dlite_material_001_lights;
extern Lights1 jrb_dl_noise_001_lights;
extern Lights1 jrb_dl_f3dlite_material_004_lights;
extern Lights1 jrb_dl_noise_002_lights;
extern Lights1 jrb_dl_f3dlite_material_008_lights;
extern Lights1 jrb_dl_noise_003_lights;
extern Lights1 jrb_dl_f3dlite_material_011_lights;
extern Lights1 jrb_dl_noise_004_lights;
extern Lights1 jrb_dl_f3dlite_material_014_lights;
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8[];
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16[];
extern u8 jrb_dl_Moon_i8[];
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_copy[];
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16_copy[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16_copy[];
extern u8 jrb_dl_Moon_i8_copy[];
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_copy_copy[];
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16_copy_copy[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16_copy_copy[];
extern u8 jrb_dl_Moon_i8_copy_copy[];
extern u8 jrb_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8[];
extern u8 jrb_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_pal_rgba16[];
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_copy_copy_copy[];
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16_copy_copy_copy[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16_copy_copy_copy[];
extern u8 jrb_dl_Moon_i8_copy_copy_copy[];
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_copy_copy_copy_copy[];
extern u8 jrb_dl__1Xyf6KR_Am4WLk_IoP3Y2iUsHj5Ox2VKMh0ZXdbvS_ci8_pal_rgba16_copy_copy_copy_copy[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16_copy_copy_copy_copy[];
extern u8 jrb_dl_Moon_i8_copy_copy_copy_copy[];
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_mesh_layer_5_vtx_0[32];
extern Gfx jrb_dl_Cube_mesh_layer_5_tri_0[];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_001_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_001_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_001_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_001_mesh_layer_5_vtx_0[32];
extern Gfx jrb_dl_Cube_001_mesh_layer_5_tri_0[];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_002_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_002_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_002_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_002_mesh_layer_5_vtx_0[32];
extern Gfx jrb_dl_Cube_002_mesh_layer_5_tri_0[];
extern Vtx jrb_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_World_mesh_layer_1_vtx_0[24];
extern Gfx jrb_dl_World_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_003_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_003_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_003_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_003_mesh_layer_5_vtx_0[32];
extern Gfx jrb_dl_Cube_003_mesh_layer_5_tri_0[];
extern Vtx jrb_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_004_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_004_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_004_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_004_mesh_layer_5_vtx_0[32];
extern Gfx jrb_dl_Cube_004_mesh_layer_5_tri_0[];
extern Vtx jrb_dl_Plane_004_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_004_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_black[];
extern Gfx mat_revert_jrb_dl_black[];
extern Gfx mat_jrb_dl_stars[];
extern Gfx mat_revert_jrb_dl_stars[];
extern Gfx mat_jrb_dl_noise[];
extern Gfx mat_revert_jrb_dl_noise[];
extern Gfx mat_jrb_dl_f3dlite_material_001[];
extern Gfx mat_jrb_dl_black_001[];
extern Gfx mat_revert_jrb_dl_black_001[];
extern Gfx mat_jrb_dl_stars_001[];
extern Gfx mat_revert_jrb_dl_stars_001[];
extern Gfx mat_jrb_dl_noise_001[];
extern Gfx mat_revert_jrb_dl_noise_001[];
extern Gfx mat_jrb_dl_f3dlite_material_004[];
extern Gfx mat_jrb_dl_black_002[];
extern Gfx mat_revert_jrb_dl_black_002[];
extern Gfx mat_jrb_dl_stars_002[];
extern Gfx mat_revert_jrb_dl_stars_002[];
extern Gfx mat_jrb_dl_noise_002[];
extern Gfx mat_revert_jrb_dl_noise_002[];
extern Gfx mat_jrb_dl_f3dlite_material_008[];
extern Gfx mat_jrb_dl_f3dlite_material_006[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_006[];
extern Gfx mat_jrb_dl_black_003[];
extern Gfx mat_revert_jrb_dl_black_003[];
extern Gfx mat_jrb_dl_stars_003[];
extern Gfx mat_revert_jrb_dl_stars_003[];
extern Gfx mat_jrb_dl_noise_003[];
extern Gfx mat_revert_jrb_dl_noise_003[];
extern Gfx mat_jrb_dl_f3dlite_material_011[];
extern Gfx mat_jrb_dl_black_004[];
extern Gfx mat_revert_jrb_dl_black_004[];
extern Gfx mat_jrb_dl_stars_004[];
extern Gfx mat_revert_jrb_dl_stars_004[];
extern Gfx mat_jrb_dl_noise_004[];
extern Gfx mat_revert_jrb_dl_noise_004[];
extern Gfx mat_jrb_dl_f3dlite_material_014[];
extern Gfx jrb_dl_Cube_mesh_layer_1[];
extern Gfx jrb_dl_Cube_mesh_layer_6[];
extern Gfx jrb_dl_Cube_mesh_layer_5[];
extern Gfx jrb_dl_Plane_mesh_layer_1[];
extern Gfx jrb_dl_Cube_001_mesh_layer_1[];
extern Gfx jrb_dl_Cube_001_mesh_layer_6[];
extern Gfx jrb_dl_Cube_001_mesh_layer_5[];
extern Gfx jrb_dl_Plane_001_mesh_layer_1[];
extern Gfx jrb_dl_Cube_002_mesh_layer_1[];
extern Gfx jrb_dl_Cube_002_mesh_layer_6[];
extern Gfx jrb_dl_Cube_002_mesh_layer_5[];
extern Gfx jrb_dl_Plane_002_mesh_layer_1[];
extern Gfx jrb_dl_World_mesh_layer_1[];
extern Gfx jrb_dl_Cube_003_mesh_layer_1[];
extern Gfx jrb_dl_Cube_003_mesh_layer_6[];
extern Gfx jrb_dl_Cube_003_mesh_layer_5[];
extern Gfx jrb_dl_Plane_003_mesh_layer_1[];
extern Gfx jrb_dl_Cube_004_mesh_layer_1[];
extern Gfx jrb_dl_Cube_004_mesh_layer_6[];
extern Gfx jrb_dl_Cube_004_mesh_layer_5[];
extern Gfx jrb_dl_Plane_004_mesh_layer_1[];
extern Gfx jrb_dl_material_revert_render_settings[];
