extern const GeoLayout jrb_area_1_geo[];
extern const GeoLayout jrb_area_1[];
extern const Collision jrb_area_1_collision[];
extern const MacroObject jrb_area_1_macro_objs[];
extern const GeoLayout jrb_area_2_geo[];
extern const GeoLayout jrb_area_2[];
extern const Collision jrb_area_2_collision[];
extern const MacroObject jrb_area_2_macro_objs[];
extern const GeoLayout jrb_area_3_geo[];
extern const GeoLayout jrb_area_3[];
extern const Collision jrb_area_3_collision[];
extern const MacroObject jrb_area_3_macro_objs[];
extern const GeoLayout jrb_area_4_geo[];
extern const GeoLayout jrb_area_4[];
extern const Collision jrb_area_4_collision[];
extern const MacroObject jrb_area_4_macro_objs[];
extern const GeoLayout jrb_area_5_geo[];
extern const GeoLayout jrb_area_5[];
extern const Collision jrb_area_5_collision[];
extern const MacroObject jrb_area_5_macro_objs[];
extern Lights1 jrb_dl_f3dlite_material_001_lights;
extern Lights1 jrb_dl_f3dlite_material_004_lights;
extern Lights1 jrb_dl_f3dlite_material_003_lights;
extern Lights1 jrb_dl_f3dlite_material_008_lights;
extern Lights1 jrb_dl_f3dlite_material_011_lights;
extern Lights1 jrb_dl_f3dlite_material_014_lights;
extern u8 jrb_dl_is_iceCaveTunnel_rgba16[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16[];
extern u8 jrb_dl__0xC20_ci4[];
extern u8 jrb_dl__0xC20_ci4_pal_rgba16[];
extern u8 jrb_dl_is_iceCaveTunnel_rgba16_copy[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16_copy[];
extern u8 jrb_dl__0xC20_ci4_copy[];
extern u8 jrb_dl__0xC20_ci4_pal_rgba16_copy[];
extern u8 jrb_dl_is_iceCaveTunnel_rgba16_copy_copy[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16_copy_copy[];
extern u8 jrb_dl__0xC20_ci4_copy_copy[];
extern u8 jrb_dl__0xC20_ci4_pal_rgba16_copy_copy[];
extern u8 jrb_dl__8_bit_luigi_ci4[];
extern u8 jrb_dl__8_bit_luigi_ci4_pal_rgba16[];
extern u8 jrb_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8[];
extern u8 jrb_dl_EARTHWORM_JIM_3D_5A0446B5_0_2_all_ci8_pal_rgba16[];
extern u8 jrb_dl_is_iceCaveTunnel_rgba16_copy_copy_copy[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16_copy_copy_copy[];
extern u8 jrb_dl__0xC20_ci4_copy_copy_copy[];
extern u8 jrb_dl__0xC20_ci4_pal_rgba16_copy_copy_copy[];
extern u8 jrb_dl_is_iceCaveTunnel_rgba16_copy_copy_copy_copy[];
extern u8 jrb_dl_GALE01_05f0c180_3_rgba16_copy_copy_copy_copy[];
extern u8 jrb_dl__0xC20_ci4_copy_copy_copy_copy[];
extern u8 jrb_dl__0xC20_ci4_pal_rgba16_copy_copy_copy_copy[];
extern Vtx jrb_dl_Cube_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_mesh_layer_6_vtx_1[32];
extern Gfx jrb_dl_Cube_mesh_layer_6_tri_1[];
extern Vtx jrb_dl_Plane_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_001_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_001_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_001_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_001_mesh_layer_6_vtx_1[32];
extern Gfx jrb_dl_Cube_001_mesh_layer_6_tri_1[];
extern Vtx jrb_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_002_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_002_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_002_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_002_mesh_layer_6_vtx_1[32];
extern Gfx jrb_dl_Cube_002_mesh_layer_6_tri_1[];
extern Vtx jrb_dl_Cube_002_mesh_layer_5_vtx_0[4];
extern Gfx jrb_dl_Cube_002_mesh_layer_5_tri_0[];
extern Vtx jrb_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_World_mesh_layer_1_vtx_0[24];
extern Gfx jrb_dl_World_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_005_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_005_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_005_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_005_mesh_layer_6_vtx_1[32];
extern Gfx jrb_dl_Cube_005_mesh_layer_6_tri_1[];
extern Vtx jrb_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_003_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx jrb_dl_Cube_003_mesh_layer_6_vtx_0[15];
extern Gfx jrb_dl_Cube_003_mesh_layer_6_tri_0[];
extern Vtx jrb_dl_Cube_003_mesh_layer_6_vtx_1[32];
extern Gfx jrb_dl_Cube_003_mesh_layer_6_tri_1[];
extern Vtx jrb_dl_Plane_004_mesh_layer_1_vtx_0[4];
extern Gfx jrb_dl_Plane_004_mesh_layer_1_tri_0[];
extern Gfx mat_jrb_dl_black[];
extern Gfx mat_revert_jrb_dl_black[];
extern Gfx mat_jrb_dl_stars[];
extern Gfx mat_revert_jrb_dl_stars[];
extern Gfx mat_jrb_dl_f3dlite_material_016[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_016[];
extern Gfx mat_jrb_dl_f3dlite_material_001[];
extern Gfx mat_jrb_dl_black_005[];
extern Gfx mat_revert_jrb_dl_black_005[];
extern Gfx mat_jrb_dl_stars_005[];
extern Gfx mat_revert_jrb_dl_stars_005[];
extern Gfx mat_jrb_dl_f3dlite_material_017[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_017[];
extern Gfx mat_jrb_dl_f3dlite_material_004[];
extern Gfx mat_jrb_dl_black_006[];
extern Gfx mat_revert_jrb_dl_black_006[];
extern Gfx mat_jrb_dl_stars_006[];
extern Gfx mat_revert_jrb_dl_stars_006[];
extern Gfx mat_jrb_dl_f3dlite_material_020[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_020[];
extern Gfx mat_jrb_dl_f3dlite_material_003[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_003[];
extern Gfx mat_jrb_dl_f3dlite_material_008[];
extern Gfx mat_jrb_dl_f3dlite_material_006[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_006[];
extern Gfx mat_jrb_dl_black_007[];
extern Gfx mat_revert_jrb_dl_black_007[];
extern Gfx mat_jrb_dl_stars_007[];
extern Gfx mat_revert_jrb_dl_stars_007[];
extern Gfx mat_jrb_dl_f3dlite_material_023[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_023[];
extern Gfx mat_jrb_dl_f3dlite_material_011[];
extern Gfx mat_jrb_dl_black_008[];
extern Gfx mat_revert_jrb_dl_black_008[];
extern Gfx mat_jrb_dl_stars_008[];
extern Gfx mat_revert_jrb_dl_stars_008[];
extern Gfx mat_jrb_dl_f3dlite_material_026[];
extern Gfx mat_revert_jrb_dl_f3dlite_material_026[];
extern Gfx mat_jrb_dl_f3dlite_material_014[];
extern Gfx jrb_dl_Cube_mesh_layer_1[];
extern Gfx jrb_dl_Cube_mesh_layer_6[];
extern Gfx jrb_dl_Plane_mesh_layer_1[];
extern Gfx jrb_dl_Cube_001_mesh_layer_1[];
extern Gfx jrb_dl_Cube_001_mesh_layer_6[];
extern Gfx jrb_dl_Plane_001_mesh_layer_1[];
extern Gfx jrb_dl_Cube_002_mesh_layer_1[];
extern Gfx jrb_dl_Cube_002_mesh_layer_6[];
extern Gfx jrb_dl_Cube_002_mesh_layer_5[];
extern Gfx jrb_dl_Plane_002_mesh_layer_1[];
extern Gfx jrb_dl_World_mesh_layer_1[];
extern Gfx jrb_dl_Cube_005_mesh_layer_1[];
extern Gfx jrb_dl_Cube_005_mesh_layer_6[];
extern Gfx jrb_dl_Plane_003_mesh_layer_1[];
extern Gfx jrb_dl_Cube_003_mesh_layer_1[];
extern Gfx jrb_dl_Cube_003_mesh_layer_6[];
extern Gfx jrb_dl_Plane_004_mesh_layer_1[];
extern Gfx jrb_dl_material_revert_render_settings[];
